use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
pub enum Severity {
    Critical,
    High,
    Medium,
    Low,
    Info,
}

/// What a record in the findings list actually is.
///
/// Engines produce two different things and the reports have to tell them
/// apart. A weakness belongs in the counts, the posture score and the
/// remediation queue. A statement about the assessment itself — how many pages
/// were reached, which were not, which third-party origins the application
/// depends on — belongs in the coverage narrative, and counting it as a finding
/// would inflate the numbers with something nobody can remediate.
///
/// Defaults to `Weakness` so records written before this existed still load,
/// and so an engine that does not set it cannot accidentally have its findings
/// filtered out of a report.
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum FindingKind {
    #[default]
    Weakness,
    /// Information about the scan's own reach, not about the target's security.
    ScanInformation,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum FindingStatus {
    Open,
    InProgress,
    Remediated,
    AcceptedRisk,
    FalsePositive,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CVSS4Data {
    /// Full CVSS 4.0 vector string (e.g. CVSS:4.0/AV:N/AC:L/...)
    pub vector_string: String,
    pub base_score: f64,
    /// Human-readable label: Critical / High / Medium / Low / None
    pub severity_label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct EPSSData {
    pub score: f64,
    pub percentile: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Evidence {
    pub evidence_type: String, // e.g. "http_request", "http_response", "code_snippet", "dependency_lock"
    pub title: String,
    pub content: String,
    pub hash: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AITriage {
    pub is_false_positive_confidence: f64,
    pub cluster_id: Option<String>,
    pub triage_notes: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Finding {
    pub id: Uuid,
    pub scan_id: Uuid,
    pub target_id: Uuid,
    pub title: String,
    pub description: String,
    pub severity: Severity,
    /// Whether this is a weakness or a statement about the assessment itself.
    #[serde(default)]
    pub kind: FindingKind,
    
    pub cvss4: Option<CVSS4Data>,
    pub epss: Option<EPSSData>,
    pub kev_listed: bool,
    pub asset_exposure_factor: f64, // 0.8 (internal) to 1.2 (public internet)
    pub reachability_score: f64,    // 0.7 (SAST unverified) to 1.2 (SAST+DAST verified)
    pub priority_score: f64,        // Integrated priority score [0.0 - 10.0]
    
    // Taxonomy Mappings
    pub cwe_id: Option<String>,        // e.g. "CWE-89"
    pub owasp_2025: Option<String>,    // e.g. "A01:2025-Broken Access Control"
    pub wstg_id: Option<String>,       // e.g. "WSTG-INPV-05"
    pub api_top10: Option<String>,     // e.g. "API1:2023-BOLA"
    
    pub affected_component: String,   // Source code path (file:line) or HTTP URL endpoint
    pub evidences: Vec<Evidence>,
    pub repro_steps: Vec<String>,
    pub remediation: String,
    pub references: Vec<String>,
    pub status: FindingStatus,
    pub source_tools: Vec<String>,    // e.g. ["Semgrep SAST", "OWASP ZAP"]
    pub ai_triage: Option<AITriage>,
    /// Human-readable scoring rationale, generated by PriorityScoringEngine::explain().
    /// Example: "CVSS4 9.3 × EPSS 92% × KEV × Reachability 1.2× = Priority 9.8"
    pub priority_rationale: String,
    pub created_at: DateTime<Utc>,
}
